engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: "config/eslintrc.js"
    extensions:
      - .js
      - .jsx
  csslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
    - "**.js"
    - "**.jsx"
    - "**.css"
    - "**.md"
