engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
  eslint:
    enabled: true
    config:
      config: "config/.eslintrc"
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
    - "**.js"
    - "**.md"
