language: node_js
sudo: false
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - istanbul ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
notifications:
  email: false
