language: node_js
dist: trusty
sudo: false
node_js:
  - 4
  - 6
  - stable
cache:
  directories:
    - node_modules
before_install:
  - if [[ `npm -v` == 2* ]]; then npm install -g npm@3; fi
  - npm install -g codecov
install:
  - npm install react react-dom
  - npm install
  - npm run demo:install
script:
  - npm run lint
  - npm test
  - npm run demo:lint
  - npm run demo:test
  - npm run demo:build
  - npm run demo:transpile
after_script:
  - npm run demo:uninstall
after_success:
  - codecov
notifications:
  email: false
