language: node_js
sudo: false
dist: trusty
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
before_install: if [[ `npm -v` == 2* ]]; then npm i -g npm@3; fi
install:
  - npm install
  - npm run demo:install
script:
  - npm run lint
  - npm run cover
  - npm run demo:lint
  - npm run demo:build
after_script:
  - npm run demo:uninstall
notifications:
  email: false
