language: node_js
sudo: false
dist: trusty
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run cover
notifications:
  email: false
